//
//  Words.swift
//  Chicago Train Tracker
//
//  Created by David Khachatryan on 3/24/24.
//

import Foundation
import SwiftUI

// Dictionary to store language translations
let words: [String: [String: String]] = [
    "hy": [
        "languageViewTitle": "Լեզուներ",
        "languageViewDisclaimer": "Սա միայն կփոխի հավելվածի լեզուն: համակարգի վրա ազդեցություն չի լինի:",
        "languageChanged": "Լեզուն փոխվեց",
        "armenian": "Հայերեն",
        "english": "Անգլերեն (English)",
        "polish": "Լեհերեն (Polish)",
        "spanish": "Իսպաներեն (Spanish)",
        "unknown": "Անհայտ",
        "restartForChanges": "Հավելվածը ռեստարտ արեք, որպեսզի փոփոխություններն ուժի մեջ մտնեն:",
        "favoriteStation": "Սիրված Կայարաններ",
        "preferenceViewTitle": "Նախընտրություններ",
        "whyAddFavorites": "Ինչու՞ ավելացնել սիրելի կայարաններ",
        "favoritesAreUsed": "Նախընտրություններն օգտագործվում են նշումներում և վիդջեթներում ձեր օպտիմալ կայարանը որոշելու համար:",
        "pleaseSelectAlwaysAllow": "Եթե ցանկանում եք, որ վիջեթը ցուցադրի ձեզ ամենամոտ կայանը, խնդրում ենք ընտրել",
        "alwaysAllow": "Միշտ",
        "inLocationSettings": "ձեր տեղանքային կարգավորումներում",
        "search": "Որոնել",
        "addFavorite": "Ավելացնել սիրելի կայաններ",
        "map": "Քարտեզ",
        "stations": "'L' կայարաններ",
        "alerts": "Նշումներ",
        "loading": "Բեռնվում է...",
        "closestStations": "Ամենամոտ կայարաններ",
        "otherStations": "Այլ կայարաններ",
        "hasNotLeftTheDepot": "",
        "elevatedServiceToward": "Վերգետնյա գնացք դեպի",
        "subwayServiceToward": "Մետրո դեպի",
        "serviceToward": "Գնացք դեպի",
        "oHareAirportTerminalArrival": "Օ'Հեյր միջազգային օդանավակայան",
        "midwayArrival": "Միդվեյ միջազգային օդանավակայան",
        "terminalArrival": "Վերջին կայարան",
        "arrival": "Կայարան",
        "terminalArrival2": "Վերջին կայարան",
        "redLineTerminalArrival": "Կարմիր գծի վերջին կայարան",
        "serviceAtInnerLoopPlatform": "Լուփի ներքին պլատֆորմ",
        "serviceAtOuterLoopPlatform": "Լուփի արտաքին պլատֆորմ",
        "lastUpdated": "Վերջին թարմացում",
        "asOf": "Ժամը",
        "use24HourFormat": "24-ժամյա ձևաչափ",
        "start": "Սկիզբ",
        "end": "Ավարտ",
        "yellowLine": "Դեղին գիծ",
        "pinkLine": "Վարդագույն գիծ",
        "orangeLine": "Նարնջագույն գիծ",
        "greenLine": "Կանաչ գիծ",
        "purpleLine": "Մանուշակագույն գիծ",
        "brownLine": "Շագանակագույն գիծ",
        "blueLine": "Կապույտ գիծ",
        "redLine": "Կարմիր գիծ",
        "allRoute": "Բոլոր երթուղիներ",
        "busRoutes": "Ավտոբուսային գծեր",
        "routes": "Գծեր",
        "alertTypes": "Նշումների տեսակներ",
        "trainRoute": "Գնացքի երթուղի",
        "trainStation": "Գնացքի կայարան",
        "systemWide": "Ամբողջ համակարգ",
        "busRoute": "Ավտոբուսի երթուղի",
        "allTypes": "Բոլոր Նշումներ",
        "hoorayNoAlerts": "Նշումներ չկան",
        "noAlertsDetailed": "Երևում է, որ գնացքներն ու ավտոբուսները հանգիստ օր են ունենում:",
        "delayed": "Ուշացած",
        "due": "Հիմա",
        "min": "րոպե",
        "detailInfoPartOne": "Ներողություն ենք խնդրում,",
        "detailInfoPartTwo": "-ի վերաբերյալ մանրամասն տեղեկատվություն ներկայումս հասանելի չէ",
        "noTrainsMessage": "Գնացքները արձակուրդի են",
        "outOfRange": "Վա՜յ: Դուք այլևս Չիկագոյում չեք: Հուսով եմ, որ ձմեռն ավելի տաք է, որտեղ որ գտնվում եք:",
        "favoriteRoute": "Սիրելի Ուղիներ",
        "addToSeePersonalAlerts": "Ավելացրեք սիրելի կայաններ անհատականացված նշումներ տեսնելու համար",
        "noPreferredRoutes": "Դեռևս սիրելի գծեր չկան",
        "alertsFailed": "Այս պահին նշումները հասանելի չեն: Խնդրում ենք նորից ստուգել ավելի ուշ:",
        "pressHoldWidget": "Սեղմեք և պահեք վիջեթը՝ կայան ընտրելու համար",
        "showLiveTransit": "Ցույց տալ լայվ գնացքները/ավտոբուսները քարտեզի վրա",
        "showAccessibilityInfo": "Ցույց տալ հասանելիության տվյալները",
        "stationDisplayInfo": "Կայարանի ժամանակացույց",
        "chooseAppIcon": "Փոխել հավելվածի այքոնը",
        "pride": "Փրայդ",
        "default": "Դեֆոլտ",
        "widgets": "Վիդջեթներ",
        "siri": "Սիրի",
        "about": "Մեր մասին",
        "feedback": "Հետադարձ կապ",
        "termsOfUse": "Ընդհանուր դրույթներ և պայմաններ",
        "privacyPolicy": "Օգտատերերի գաղտնիություն",
        "version": "Տարբերակ",
        "general": "Ընդհանուր",
        "legal": "Իրավական",
        "ctaColors": "CTA-ի գույներ",
        "useLegacyMap": "Օգտագործել հին քարտեզ",
        "to": "դեպի",
        "appearance": "Տեսք",
        "system": "Սիստեմ",
        "light": "Բաց",
        "dark": "Մուգ",
        "justNow": "Հիմա",
        "minAgo": "րոպե",
        "minsAgo": "րոպե",
        "likeELTracker": "Հավանու՞մ եք EL Tracker-ը",
        "followOnTwitter": "Հետևեք մեզ Twitter-ում",
        "followOnIG": "Հետևեք մեզ Instagram-ում",
        "donate": "Նվիրաբերեք՝ EL Tracker-ը անվճար պահելու համար",
        "aboutDetail": """
                            Մենք Չիկագոյի բնակիչներ և CTA «L» գնացքների օգտատերեր ենք, որոնք զայրացած էին Չիկագոյի տրանսպորտի պարզ հավելվածի բացակայությունից: Մի օր մենք ասացինք. «Ինչու՞ չեմ կարող ունենալ վիջեթ, որը ցույց կտա, թե երբ է գալիս գնացքը»:
                        
                            Եվ այսպես ծնվեց EL Tracker-ը: Այնտեղից գաղափարը միայն աճեց: Այժմ մենք ունենք հավելված, որը հստակ և օգտատիրական ձևաչափով ցույց է տալիս գնացքների ժամանումը, միաժամանակ ավելացնելով այլ օգտակար գործառույթներ, ինչպիսիք են. քարտեզի ինտեգրումը գնացքների ուղիղ լոկացիայի հետ, Siri-ի աջակցությունը, բազմալեզու լինելը և վիջեթները:
                        
                            Այս հավելվածը չի արժանացել CTA-ի պաշտոնական հավանությանը: Հավաստիության երաշխիքներ տալու համար մենք հետևել ենք CTA-ի երրորդ կողմի ծառայության API փաստաթղթերում ներկայացված բոլոր մշակողների առաջարկներին:
                        
                        Ստեղծվել է Դավիթ Խաչատրյանի, Ջեմմա ԴեՍետրայի և Ուիլ Ֆիլիպսի կողմից:
                        """,
        "widgetDetailOne": "Կարգավորեք վիջեթները ուղիղ տան էկրանից՝ երկար սեղմելով վիջեթի վրա և ընտրելով \"Խմբագրել վիջեթը\"",
        "widgetDetailTwo": "\"Ամենամոտ կայարանի\" վիջեթը օգտագործելու համար խնդրում ենք Միշտ թույլատրել տեղադրությունը EL Tracker-ի համար:",
        "smartWalkDetail": """
        SmartWalk ֆունկցիան հաշվում է ձեր քայլելու ժամանակը մինչեւ կայարան, եւ ցուցադրում է միայն այդ քայլելու ժամանակից հետո եկող գնացքների ժամանումները: Խնդրում ենք Միշտ թույլատրել տեղադրությունը EL Tracker-ի համար:
        """,
        "siriDetail":   """
                        Օգտագործեք Սիրի՝ հարցնելով.
                        
                        "When is the next train on El Tracker?"

                        կամ
                        
                        Դուք կարող եք ստեղծել shortcut-ներ և կարգավորել երթուղին CTA-ի համար (Կարմիր գիծ, Կապույտ գիծ և այլն): Shortcut-ը ցույց կտա գնացքների ժամանումները՝ ըստ ձեր ընտրած երթուղու:
                        
                        Սիրին հասանելի է միայն անգլերեն լեզվով:
                        """,
        "notifications": "Ծանուցումներ",
        "trains": "Գնացքներ",
        "buses": "Ավտոբուսներ",
        "advancedSettings": "Ընդլայնված Կարգավորումներ",
        "favoritesWillBeFirst": "Սիրված երթուղիները միշտ առաջին տեղում կլինեն վիջեթներում և Սիրիի պատասխաններում:",
        "ridingThePartOne": "Ավելի շատ",
        "ridingThePartTwo": "-ով քան",
        "ridingThePartThree": "-ով ե՞ք երթևեկում: Կարգավորեք ձեր նախընտրություններն այստեղ։",
        "youWillOnlyReceive": "Դուք կստանաք ծանուցումներ միայն ձեր նախընտրած կայարանների/ուղիների համար, եթե վերջին կարգավորումը չի միացված:",
        "receiveTrainNotifications": "Ստանալ ծանուցումներ սիրելի կայարաններում/գծերում ահազանգերի համար",
        "receiveStationNotifications": "Ստանալ կայարանների ծանուցումներ",
        "experimentalFeature": "Սա փորձնական թարգմանություն է: CTA նշումների թարգմանությունները պաշտոնական չեն և կարող են իմաստ չունենալ։",
        "translateAlerts": "Թարգմանել նշումները",
        "notRecommended": "Խորհուրդ չի տրվում միացնել: Դուք ծանուցում կստանաք բոլոր գծերի և կայարանների համար:",
        "notificationsForAll": "Ստանալ բոլոր CTA համակարգի ծանուցումները",
        "stationsLiteral": "կայարաններ",
        "or": "կամ",
        "lines": "գծեր",
        "signUpForNotifications": "ծանուցումներ ստանալու համար",
        "addFavoriteLiteral": "Ավելացնել սիրելի",
        "smartWalkExplanation": "SmartWalk",
        "time": "Ժամանակ",
        "countdown": "Հետհաշվարկ (2 րոպե)",
        "12hour": "12-ժամ (9:20 PM)",
        "24hour": "24-ժամ (21:20)",
        "pleaseAlwaysAllow": "Խնդրում ենք ընտրել միշտ թույլատրել ձեր տեղադրության կարգավորումներում՝ ամենամոտիկ կանգառը տեսնելու համար: Փոփոխությունները կարող են ուժի մեջ մտնել մինչեւ 15 րոպե անց:",
    ],
    "en": [
        "languageViewTitle": "Language",
        "languageViewDisclaimer": "This will only change the language in-app. No system impact.",
        "languageChanged": "Language changed",
        "armenian": "Armenian",
        "english": "English",
        "polish": "Polish",
        "spanish": "Spanish",
        "unknown": "Unknown",
        "restartForChanges": "Restart the app for changes to take effect",
        "favoriteStation": "Favorite Stations",
        "preferenceViewTitle": "Preferences",
        "whyAddFavorites": "Why add favorites?",
        "favoritesAreUsed": "Favorites are used to determine your default station used for alerts and widgets. ",
        "pleaseSelectAlwaysAllow": "If you would like the widget to display the station closest to you, please select",
        "alwaysAllow": "Always",
        "inLocationSettings": "in your location settings.",
        "search": "Search",
        "addFavorite": "Add Favorite",
        "map": "Map",
        "stations": "'L' Stations",
        "alerts": "Alerts",
        "loading": "Loading...",
        "closestStations": "Closest Stations",
        "otherStations": "Other Stations",
        "hasNotLeftTheDepot": "has not left the train depot",
        "elevatedServiceToward": "Elevated service toward",
        "subwayServiceToward": "Subway service toward",
        "serviceToward": "Service toward",
        "oHareAirportTerminalArrival": "O'Hare International Airport",
        "midwayArrival": "Midway International Airport",
        "terminalArrival": "Terminal Arrival",
        "arrival": "Arrival",
        "terminalArrival2": "Terminal arrival",
        "redLineTerminalArrival": "Red Line Terminal Arrival",
        "serviceAtInnerLoopPlatform": "Service at Inner Loop platform",
        "serviceAtOuterLoopPlatform": "Service at Outer Loop platform",
        "lastUpdated": "Last Updated",
        "use24HourFormat": "Use 24-Hour Format",
        "start": "Start",
        "end": "End",
        "yellowLine": "Yellow Line",
        "pinkLine": "Pink Line",
        "orangeLine": "Orange Line",
        "greenLine": "Green Line",
        "purpleLine": "Purple Line",
        "brownLine": "Brown Line",
        "blueLine": "Blue Line",
        "redLine": "Red Line",
        "allRoute": "All Lines",
        "busRoutes": "Bus Lines",
        "routes": "Lines",
        "alertTypes": "Alert Types",
        "trainRoute": "Train Route",
        "trainStation": "Train Station",
        "systemWide": "System Wide",
        "busRoute": "Bus Route",
        "allTypes": "All Types",
        "hoorayNoAlerts": "Hooray! No alerts!",
        "noAlertsDetailed": "Looks like the trains and buses are having a smooth day. Keep riding with joy!",
        "delayed": "Delayed",
        "due": "Due",
        "min": "min",
        "detailInfoPartOne": "We’re sorry, detailed information for",
        "detailInfoPartTwo": "is not currently available.",
        "noTrainsMessage": "Trains are on a smoke break",
        "outOfRange": "Uh-oh! Looks like you are out of range. Hope the winter is warmer wherever you are.",
        "favoriteRoute": "Favorite Lines",
        "addToSeePersonalAlerts": "Add favorite stations to see personalized alerts!",
        "noPreferredRoutes": "No Preferred Lines",
        "alertsFailed": "Alerts are not available at the moment. Please check back later.",
        "pressHoldWidget": "Press and hold the widget to edit and select a station",
        "showLiveTransit": "Show Live Trains/Buses on Map",
        "showAccessibilityInfo": "Show Accessibility Info",
        "stationDisplayInfo": "Station Display Information",
        "chooseAppIcon": "Change App Icon",
        "pride": "Pride",
        "default": "Default",
        "widgets": "Widgets",
        "siri": "Siri",
        "about": "About",
        "feedback": "Feedback",
        "termsOfUse": "Terms of Use",
        "privacyPolicy": "Privacy Policy",
        "version": "Version",
        "general": "General",
        "legal": "Legal",
        "ctaColors": "CTA colors",
        "useLegacyMaps": "Use Legacy Map",
        "to": "to",
        "appearance": "Appearance",
        "system": "System",
        "light": "Light",
        "dark": "Dark",
        "justNow": "Just Now",
        "minAgo": "min ago",
        "minsAgo": "mins ago",
        "followOnTwitter": "Follow on Twitter",
        "followOnIG": "Follow on Instagram",
        "likeELTracker": "Like EL Tracker?",
        "donate": "Donate to keep EL Tracker free",
        "aboutDetail": """
                            We are fellow Chicago residents and CTA 'L' riders who were irritated by the lack of a simple Chicago transit app. One night, we said, \"Why can't I have a widget that shows me when the train is coming?\"
                                        
                            And thus, EL Tracker was born. From there, the idea only grew.  We now have an app that shows arrival times in a simple, user-friendly format, while adding other helpful features like map integration with live train locations, Siri support, multiple languages, and widgets.
                                        
                            This app is not officially endorsed by the CTA. To guarantee reliability we have followed all the developer suggestions laid out in the CTA third-party service API documentation.
                                        
                        Created by David Khachatryan, Gemma DeCetra, Will Phillips
                        """,
        "widgetDetailOne": "Configure widgets directly from the home screen by long-pressing the widget and selecting \"Edit Widget.\"",
        "widgetDetailTwo": "To use \"Closest Station\" widget, please be sure to Always Allow location for EL Tracker.",
        "smartWalkDetail": """
                        The SmartWalk feature calculates your walking time to the station, and only displays arrivals after that walk time. Please be sure to Always Allow location for EL Tracker.
                        """,
        "siriDetail":   """
                        Use Siri by asking:
                        
                        "When is the next train on El Tracker?"
                        
                        or
                        
                        You can also set up shortcuts and configure the route for the CTA (Red line, Blue line, etc.). The shortcut will show train arrivals from the route you choose as an input.
                        
                        Siri is only available in English.
                        """,
        "notifications": "Notifications",
        "trains": "Trains",
        "buses": "Buses",
        "advancedSettings": "Advanced Settings",
        "favoritesWillBeFirst": "Favorite lines will always be first on the widgets, and Siri responses",
        "ridingThePartOne": "Riding the",
        "ridingThePartTwo": "more than the",
        "ridingThePartThree": "? Order your preference here!",
        "youWillOnlyReceive": "You will only receive notifications for your favorites, unless the last setting is turned on.",
        "receiveTrainNotifications": "Receive Push Notifications for Alerts at Favorite Stations/Lines",
        "receiveStationNotifications": "Receive Train Station Notifications",
        "experimentalFeature": "This is an experimental feature. Translations of CTA Alerts are not official and may not make sense.",
        "translateAlerts": "Translate Alerts",
        "notRecommended": "Not recommended to turn on. You will receive every alert as a notification.",
        "notificationsForAll": "Receive All CTA System Alerts",
        "stationsLiteral": "stations",
        "or": "or",
        "lines": "lines",
        "signUpForNotifications": "to sign up for notifications",
        "addFavoriteLiteral": "Add favorite",
        "smartWalkExplanation": "The SmartWalk widget, available with 'Closest Stop' and 'Always Allow' location setting, shows only trains arriving after you can walk to the nearest station.",
        "time": "Time",
        "countdown": "Countdown (2 min)",
        "12hour": "12-Hour (9:20 PM)",
        "24hour": "24-Hour (21:20)",
        "pleaseAlwaysAllow": "Please select always allow in your location settings to see the closest stop. Changes may take up to 15 minutes to take effect.",
    ],
    "es": [
        "languageViewTitle": "Idioma",
        "languageViewDisclaimer": "Esto solo cambiará el idioma en la aplicación. Sin impacto en el sistema.",
        "languageChanged": "Idioma cambiado",
        "armenian": "Armenio",
        "english": "Inglés",
        "polish": "Polaco",
        "spanish": "Español",
        "unknown": "Desconocido",
        "restartForChanges": "Reinicie la aplicación para que los cambios surtan efecto",
        "favoriteStation": "Estaciones Favoritas",
        "preferenceViewTitle": "Preferencias",
        "whyAddFavorites": "Por qué agregar favoritos?",
        "favoritesAreUsed": "Los favoritos se utilizan para determinar su estación predeterminada utilizada para alertas y widgets.",
        "pleaseSelectAlwaysAllow": "Si desea que el widget muestre la estación más cercana a usted, seleccione",
        "alwaysAllow": "Siempre",
        "inLocationSettings": "en la configuración de su ubicación.",
        "search": "Buscar",
        "addFavorite": "Agregar favorito",
        "map": "Mapa",
        "stations": "Estaciones 'L'",
        "alerts": "Alertas",
        "loading": "Cargando...",
        "closestStations": "Estaciones más cercanas",
        "otherStations": "Otras estaciones",
        "hasNotLeftTheDepot": "",
        "elevatedServiceToward": "Servicio elevado hacia",
        "subwayServiceToward": "Servicio de metro hacia",
        "serviceToward": "Servicio hacia",
        "oHareAirportTerminalArrival": "Aeropuerto Internacional O'Hare",
        "midwayArrival": "Llegada a Midway",
        "terminalArrival": "Llegada a terminal",
        "arrival": "Llegada",
        "terminalArrival2": "Llegada a terminal",
        "redLineTerminalArrival": "Llegada a Terminal de Línea Roja",
        "serviceAtInnerLoopPlatform": "Servicio en plataforma de Loop interior",
        "serviceAtOuterLoopPlatform": "Servicio en plataforma de Loop exterior",
        "lastUpdated": "Última actualización",
        "asOf": "A las",
        "use24HourFormat": "Reloj de 24 horas",
        "start": "Inicio",
        "end": "Fin",
        "yellowLine": "Línea Amarilla",
        "pinkLine": "Línea Rosa",
        "orangeLine": "Línea Naranja",
        "greenLine": "Línea Verde",
        "purpleLine": "Línea Morada",
        "brownLine": "Línea Marrón",
        "blueLine": "Línea Azul",
        "redLine": "Línea Roja",
        "allRoute": "Todas las Líneas",
        "busRoutes": "Lineas de Autobús",
        "routes": "Lineas",
        "alertTypes": "Tipos de Alerta",
        "trainRoute": "Ruta de Tren",
        "trainStation": "Estación de Tren",
        "systemWide": "Todo el Sistema",
        "busRoute": "Ruta de Autobús",
        "allTypes": "Todos los tipos",
        "hoorayNoAlerts": "¡Hurra! ¡No hay alertas!",
        "noAlertsDetailed": "Parece que los trenes y autobuses están teniendo un día sin problemas. ¡Sigan viajando con alegría!",
        "delayed": "Tardío",
        "due": "Ahora",
        "min": "min",
        "detailInfoPartOne": "Lo sentimos, la información detallada sobre la",
        "detailInfoPartTwo": "no está disponible actualmente.",
        "noTrainsMessage": "Los trenes están en una pausa para fumar",
        "outOfRange": "¡Uh-oh! Parece que estás fuera de rango. Espero que el invierno sea más cálido dondequiera que estés.",
        "favoriteRoute": "Líneas Favoritas",
        "addToSeePersonalAlerts": "¡Añade estaciones favoritas para ver alertas personalizadas!",
        "noPreferredRoutes": "Sin lineas favoritas",
        "alertsFailed": "Las alertas no están disponibles en este momento. Por favor, vuelva más tarde.",
        "pressHoldWidget": "Mantenga presionado el widget para seleccionar una estación",
        "showAccessibilityInfo": "Mostrar información de accesibilidad",
        "showLiveTransit": "Mostrar trenes/autobuses en vivo en el mapa",
        "stationDisplayInfo": "Información de la estación",
        "chooseAppIcon": "Cambiar icono de aplicación",
        "pride": "Orgullo",
        "default": "Por defecto",
        "widgets": "Widgets",
        "siri": "Siri",
        "about": "Información",
        "feedback": "El feedback",
        "termsOfUse": "Condiciones de uso",
        "privacyPolicy": "Política de privacidad",
        "version": "Versión",
        "general": "General",
        "legal": "Legal",
        "ctaColors": "Colores de CTA",
        "useLegacyMap": "Usar mapa legado",
        "to": "a",
        "appearance": "Apariencia",
        "system": "Sistema",
        "light": "Ligero",
        "dark": "Oscuro",
        "justNow": "Ahora",
        "minAgo": "Minuto",
        "minsAgo": "Minutos",
        "followOnTwitter": "Seguir en Twitter",
        "followOnIG": "Seguir en Instagram",
        "likeELTracker": "Te gusta EL Tracker?",
        "donate": "Done para mantener EL Tracker gratuito",
        "aboutDetail": """
                            Éramos residentes de Chicago y usuarios del tren 'L' del CTA que estábamos irritados por la falta de una simple aplicación de tránsito de Chicago. Una noche, dijimos: "¿Por qué no puedo tener un widget que me muestre cuándo viene el tren?"
                        
                            Y así nació EL Tracker. Desde ahí, la idea solo creció. Ahora tenemos una aplicación que muestra los tiempos de llegada en un formato simple y fácil de usar, mientras agrega otras funciones útiles como la integración de mapas con ubicaciones de trenes en vivo, soporte para Siri, múltiples idiomas y widgets.
                        
                            Esta aplicación no está respaldada oficialmente por el CTA. Para garantizar la confiabilidad, hemos seguido todas las sugerencias de los desarrolladores descritas en la documentación de la API del servicio de terceros del CTA.
                        
                        Creado por David Khachatryan, Gemma DeCetra, Will Phillips
                        """,
        "widgetDetailOne": "Configure los widgets directamente desde la pantalla de inicio manteniendo presionado el widget y seleccionando \"Editar widget\"",
        "widgetDetailTwo": "Para usar el widget \"Estación más cercana\", asegúrese de Permitir siempre la ubicación para EL Tracker.",
        "smartWalkDetail": """
        La función SmartWalk calcula el tiempo que tardará en caminar hasta la estación y solo muestra las llegadas después de ese tiempo de caminata. Asegúrese de Permitir siempre la ubicación para EL Tracker.
        """,
        "siriDetail":   """
                        Usa Siri preguntando:
                        
                        "When is the next train on El Tracker?"
                        
                        o
                        
                        También puedes configurar atajos y configurar la ruta para el CTA (Línea Roja, Línea Azul, etc.). El atajo mostrará las llegadas de trenes desde la ruta que elijas como entrada.
                        
                        Siri sólo está disponible en inglés.
                        """,
        "notifications": "Notificaciones",
        "trains": "Trenes",
        "buses": "Autobuses",
        "advancedSettings": "Ajustes Avanzados",
        "favoritesWillBeFirst": "Las líneas favoritas siempre serán las primeras en los widgets y las respuestas de Siri.",
        "ridingThePartOne": "Viajar en el",
        "ridingThePartTwo": "más que en el",
        "ridingThePartThree": "? ¡Ordena tu preferencia aquí!",
        "youWillOnlyReceive": "Solo recibirás notificaciones de tus favoritos, a menos que se active la última configuración.",
        "receiveTrainNotifications": "Recibir notificaciones push para alertas en estaciones/líneas favoritas",
        "receiveStationNotifications": "Recibir notificaciones de estaciones de tren",
        "experimentalFeature": "Esta es una función experimental. Las traducciones de las alertas de CTA no son oficiales y pueden carecer de sentido.",
        "translateAlerts": "Traducir alertas",
        "notRecommended": "No se recomienda activar. Recibirás todas las alertas como notificación.",
        "notificationsForAll": "Recibir todas las alertas del sistema CTA",
        "stationsLiteral": "estaciones",
        "or": "o",
        "lines": "líneas",
        "signUpForNotifications": "para registrarse para recibir notificaciones",
        "addFavoriteLiteral": "Agregar favoritas",
        "smartWalkExplanation": "El widget SmartWalk, disponible con la configuración 'Estacion más cercana' y 'Permitir siempre' la ubicación, solo muestra los trenes que llegan después de que puedas caminar a la estación más cercana.",
        "time": "Hora",
        "countdown": "Cuenta regresiva (2 min)",
        "12hour": "12-hora (9:20 PM)",
        "24hour": "24-hora (21:20)",
        "pleaseAlwaysAllow": "Seleccione \"Permitir siempre\" en la configuración de ubicación para ver la parada más cercana. Los cambios pueden tardar hasta 15 minutos en surtir efecto.",
    ],
    "pl": [
        "languageViewTitle": "Język",
        "languageViewDisclaimer": "Spowoduje to jedynie zmianę języka w aplikacji. Brak wpływu na system.",
        "languageChanged": "Język zmieniony",
        "armenian": "Ormiański",
        "english": "Angielski",
        "polish": "Polski",
        "spanish": "Hiszpański",
        "unknown": "Nieznany",
        "restartForChanges": "Uruchom ponownie aplikację, aby zmiany zaczęły obowiązywać",
        "favoriteStation": "Preferowane Stacje",
        "preferenceViewTitle": "Preferencje",
        "whyAddFavorites": "Po co dodawać preferencje?",
        "favoritesAreUsed": "Preferencje służą do określenia domyślnej stacji używanej do alertów i widżetów.",
        "pleaseSelectAlwaysAllow": "Jeśli chcesz, aby widżet wyświetlał stację najbliżej Ciebie, wybierz opcję",
        "alwaysAllow": "Zawsze",
        "inLocationSettings": "w ustawieniach położenie",
        "search": "Szukaj",
        "addFavorite": "Dodaj preferowaną stację",
        "map": "Mapa",
        "stations": "Stacje 'L'",
        "alerts": "Alerty",
        "loading": "Ładowanie...",
        "closestStations": "Najbliższe stacje",
        "otherStations": "Inne stacje",
        "hasNotLeftTheDepot": "",
        "elevatedServiceToward": "Usługa w kierunku podwyższonym",
        "subwayServiceToward": "Usługa w kierunku metra",
        "serviceToward": "Usługa w kierunku",
        "oHareAirportTerminalArrival": "Międzynarodowe Lotnisko O'Hare",
        "midwayArrival": "Międzynarodowy Lotnisko Midway",
        "terminalArrival": "Przylot na terminal",
        "arrival": "Przylot",
        "terminalArrival2": "Przylot na terminal",
        "redLineTerminalArrival": "Przylot na Terminal Linii Czerwonej",
        "serviceAtInnerLoopPlatform": "Usługa na platformie wewnętrznego Loop",
        "serviceAtOuterLoopPlatform": "Usługa na platformie zewnętrznego Loop",
        "lastUpdated": "Ostatnio zaktualizowany",
        "asOf": "Od",
        "use24HourFormat": "Czas 24-godzinny",
        "start": "Początek",
        "end": "Koniec",
        "yellowLine": "Żółta Linia",
        "pinkLine": "Różowa Linia",
        "orangeLine": "Pomarańczowa Linia",
        "greenLine": "Zielona Linia",
        "purpleLine": "Fioletowa Linia",
        "brownLine": "Brązowa Linia",
        "blueLine": "Niebieska Linia",
        "redLine": "Czerwona Linia",
        "allRoute": "Wszystkie Trasy",
        "busRoutes": "Linie Autobusowe",
        "routes": "Linie",
        "alertTypes": "Typy Alertów",
        "trainRoute": "Trasa Pociągu",
        "trainStation": "Stacja Kolejowa",
        "systemWide": "Cały System",
        "busRoute": "Trasa Autobusowa",
        "allTypes": "Wszystkie typy",
        "hoorayNoAlerts": "Hurra! Brak alertów!",
        "noAlertsDetailed": "Wygląda na to, że pociągi i autobusy mają dziś spokojny dzień.",
        "delayed": "Późno",
        "due": "Teraz",
        "min": "min",
        "detailInfoPartOne": "Przepraszamy, szczegółowe informacje na temat",
        "detailInfoPartTwo": "nie są obecnie dostępne.",
        "noTrainsMessage": "Pociągi są na wakacjach",
        "outOfRange": "Uch, o nie! Wygląda na to, że jesteś poza zasięgiem. Mam nadzieję, że ta zima będzie cieplejsza, gdziekolwiek jesteś.",
        "favoriteRoute": "Preferowane Trasy",
        "addToSeePersonalAlerts": "Dodaj ulubione stacje, aby otrzymywać spersonalizowane alerty!",
        "noPreferredRoutes": "Brak preferowanych linii",
        "alertsFailed": "Alerty nie są obecnie dostępne. Sprawdź ponownie później.",
        "pressHoldWidget": "Naciśnij i przytrzymaj widget, aby wybrać stację",
        "showAccessibilityInfo": "Pokaż informacje o ułatwieniach dostępu",
        "showLiveTransit": "Pokaż pociągi/autobusy na żywo na mapie",
        "stationDisplayInfo": "Informacje o stacji",
        "chooseAppIcon": "Zmień ikonę aplikacji",
        "pride": "Pride",
        "default": "Domyślny",
        "widgets": "Widżety",
        "siri": "Siri",
        "about": "Informacja",
        "feedback": "Informacja zwrotna",
        "termsOfUse": "Warunki korzystania",
        "privacyPolicy": "Polityka prywatności",
        "version": "Wersja",
        "general": "Ogólne",
        "legal": "Prawny",
        "ctaColors": "Kolory CTA",
        "useLegacyMap": "Użyj starszej mapy",
        "to": "do",
        "appearance": "Wygląd",
        "system": "System",
        "light": "Światło",
        "dark": "Ciemny",
        "justNow": "Teraz",
        "minAgo": "minutę temu",
        "minsAgo": "minuty temu",
        "followOnTwitter": "Śledź na Twitterze",
        "followOnIG": "Śledź na Instagramie",
        "likeELTracker": "Jak EL Tracker?",
        "donate": "Przekaż darowiznę, aby EL Tracker pozostał darmowy",
        "aboutDetail": """
                            Byliśmy mieszkańcami Chicago i pasażerami pociągów "L" CTA, zirytowanymi brakiem prostej aplikacji do komunikacji miejskiej w Chicago. Pewnej nocy powiedzieliśmy: "Dlaczego nie mogę mieć widżetu, który pokaże mi, kiedy nadjedzie pociąg?"
                        
                            I tak narodziła się aplikacja EL Tracker. Od tego czasu pomysł tylko się rozrastał. Teraz mamy aplikację, która w przystępny i przyjazny dla użytkownika sposób wyświetla czasy przyjazdów, dodając jednocześnie inne przydatne funkcje, takie jak integracja z mapami z aktualnymi lokalizacjami pociągów na żywo, obsługa Siri, wiele języków i widżety.
                            
                            Ta aplikacja nie jest oficjalnie zatwierdzona przez CTA. Aby zagwarantować niezawodność, postępowaliśmy zgodnie ze wszystkimi sugestiami dla programistów przedstawionymi w dokumentacji API usługi zewnętrznej CTA.
                        
                        Utworzone przez Davida Khachatryana, Gemmę DeCetrę i Willa Phillipsa.
                        """,
        "widgetDetailOne": "Skonfiguruj widżety bezpośrednio z ekranu głównego, przytrzymując długie naciśnięcie na widżecie i wybierając \"Edytuj widżet\"",
        "widgetDetailTwo": "Aby użyć widżetu \"Najbliższa stacja\", upewnij się, że zawsze zezwalasz na lokalizację dla EL Tracker.",
        "smartWalkDetail": """
        Funkcja SmartWalk oblicza czas przejścia do stacji i wyświetla tylko przyjazdy po tym czasie przejścia. Upewnij się, że zawsze zezwalasz na lokalizację dla EL Tracker.
        """,
        "siriDetail":   """
                        Użyj Siri, pytając:
                        
                        "When is the next train on El Tracker?"
                        
                        lub
                        
                        Możesz także skonfigurować skróty i ustawić trasę dla CTA (linia czerwona, linia niebieska itp.). Skrót pokaże przyjazdy pociągów na wybranej przez Ciebie trasie.
                        
                        Siri jest dostępna tylko w języku angielskim.
                        """,
        "notifications": "Powiadomienia",
        "trains": "Pociągi",
        "buses": "Autobusy",
        "advancedSettings": "Zaawansowane Ustawienia",
        "favoritesWillBeFirst": "Preferowane trasy będą zawsze znajdować się na pierwszym miejscu w widżetach i w odpowiedziach Siri.",
        "ridingThePartOne": "Jechać częściej",
        "ridingThePartTwo": "niż",
        "ridingThePartThree": "? Uporządkuj swoje preferencje tutaj!",
        "youWillOnlyReceive": "Będziesz otrzymywać powiadomienia tylko dla ulubionych, chyba że ostatnia opcja zostanie włączona.",
        "receiveTrainNotifications": "Otrzymuj powiadomienia push dla alertów na ulubionych stacjach/liniach",
        "receiveStationNotifications": "Otrzymuj powiadomienia o stacjach kolejowych",
        "experimentalFeature": "To eksperymentalna funkcja. Tłumaczenia alertów CTA nie są oficjalne i mogą nie mieć sensu.",
        "translateAlerts": "Tłumacz alerty",
        "notRecommended": "Nie zaleca się włączania. Będziesz otrzymywać każdy alert jako powiadomienie.",
        "notificationsForAll": "Otrzymuj wszystkie alerty systemu CTA",
        "stationsLiteral": "stacje",
        "or": "lub",
        "lines": "linie",
        "signUpForNotifications": "aby zapisać się na powiadomienia",
        "addFavoriteLiteral": "Dodaj preferowane",
        "smartWalkExplanation": "Widżet SmartWalk, dostępny przy ustawieniu 'Najbliższa Stacja' i 'Zawsze Zezwalaj' na lokalizację, pokazuje tylko pociągi przybywające po dotarciu do najbliższej stacji pieszo.",
        "time": "Czas",
        "countdown": "Odliczanie (2 min)",
        "12hour": "12-godzinny (9:20 PM)",
        "24hour": "24-godzinny (21:20)",
        "pleaseAlwaysAllow": "Wybierz opcję „Zawsze zezwalaj\" w ustawieniach lokalizacji, aby zobaczyć najbliższy przystanek. Zmiany mogą wejść w życie nawet przez 15 minut.",
    ]
]
